- hosts: localhost

  become: yes
  tasks:

  # Install Docker, Modified from Jack Barkley

  - name: install prerequisites
    apt:
      name:
        - apt-transport-https
        - ca-certificates 
        - curl 
        - gnupg-agent
        - software-properties-common
      update_cache: yes

  - name: add apt-key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: add docker repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable

  - name: install docker 
    apt:
      name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
      update_cache: yes

  - name: add user to group
    user:
      name: ubuntu
      append: true
      groups: docker

  - name: Download foo.conf
    get_url:
      url: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
      dest: /tmp/minikube_latest_amd64.deb
      mode: '0444'

  - name: install minikube
    command: dpkg -i /tmp/minikube_latest_amd64.deb
